/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as LivresSlugRouteImport } from './routes/livres.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LivresSlugRoute = LivresSlugRouteImport.update({
  id: '/livres/$slug',
  path: '/livres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confidentialite'
    | '/mentions-legales'
    | '/methode'
    | '/collections/$slug'
    | '/livres/$slug'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confidentialite'
    | '/mentions-legales'
    | '/methode'
    | '/collections/$slug'
    | '/livres/$slug'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/confidentialite'
    | '/mentions-legales'
    | '/methode'
    | '/collections/$slug'
    | '/livres/$slug'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodeRoute: typeof MethodeRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  LivresSlugRoute: typeof LivresSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livres/$slug': {
      id: '/livres/$slug'
      path: '/livres/$slug'
      fullPath: '/livres/$slug'
      preLoaderRoute: typeof LivresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodeRoute: MethodeRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  LivresSlugRoute: LivresSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
