/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DesinscriptionRouteImport } from './routes/desinscription'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MethodRouteImport } from './routes/method'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CompagnonIndexRouteImport } from './routes/compagnon.index'
import { Route as CompagnonSlugRouteImport } from './routes/compagnon.$slug'
import { Route as CompanionIndexRouteImport } from './routes/companion.index'
import { Route as CompanionSlugRouteImport } from './routes/companion.$slug'
import { Route as LivresSlugRouteImport } from './routes/livres.$slug'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DesinscriptionRoute = DesinscriptionRouteImport.update({
  id: '/desinscription',
  path: '/desinscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagnonIndexRoute = CompagnonIndexRouteImport.update({
  id: '/compagnon/',
  path: '/compagnon/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagnonSlugRoute = CompagnonSlugRouteImport.update({
  id: '/compagnon/$slug',
  path: '/compagnon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionIndexRoute = CompanionIndexRouteImport.update({
  id: '/companion/',
  path: '/companion/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionSlugRoute = CompanionSlugRouteImport.update({
  id: '/companion/$slug',
  path: '/companion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LivresSlugRoute = LivresSlugRouteImport.update({
  id: '/livres/$slug',
  path: '/livres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activation': typeof ActivationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/desinscription': typeof DesinscriptionRoute
  '/legal': typeof LegalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/method': typeof MethodRoute
  '/methode': typeof MethodeRoute
  '/privacy': typeof PrivacyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/books/$slug': typeof BooksSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compagnon/$slug': typeof CompagnonSlugRoute
  '/companion/$slug': typeof CompanionSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compagnon/': typeof CompagnonIndexRoute
  '/companion/': typeof CompanionIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activation': typeof ActivationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/desinscription': typeof DesinscriptionRoute
  '/legal': typeof LegalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/method': typeof MethodRoute
  '/methode': typeof MethodeRoute
  '/privacy': typeof PrivacyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/books/$slug': typeof BooksSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compagnon/$slug': typeof CompagnonSlugRoute
  '/companion/$slug': typeof CompanionSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/compagnon': typeof CompagnonIndexRoute
  '/companion': typeof CompanionIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/activation': typeof ActivationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/desinscription': typeof DesinscriptionRoute
  '/legal': typeof LegalRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/method': typeof MethodRoute
  '/methode': typeof MethodeRoute
  '/privacy': typeof PrivacyRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/books/$slug': typeof BooksSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compagnon/$slug': typeof CompagnonSlugRoute
  '/companion/$slug': typeof CompanionSlugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compagnon/': typeof CompagnonIndexRoute
  '/companion/': typeof CompanionIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/activation'
    | '/confidentialite'
    | '/contact'
    | '/desinscription'
    | '/legal'
    | '/mentions-legales'
    | '/method'
    | '/methode'
    | '/privacy'
    | '/unsubscribe'
    | '/books/$slug'
    | '/collections/$slug'
    | '/compagnon/$slug'
    | '/companion/$slug'
    | '/livres/$slug'
    | '/collections/'
    | '/compagnon/'
    | '/companion/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/activation'
    | '/confidentialite'
    | '/contact'
    | '/desinscription'
    | '/legal'
    | '/mentions-legales'
    | '/method'
    | '/methode'
    | '/privacy'
    | '/unsubscribe'
    | '/books/$slug'
    | '/collections/$slug'
    | '/compagnon/$slug'
    | '/companion/$slug'
    | '/livres/$slug'
    | '/collections'
    | '/compagnon'
    | '/companion'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/activation'
    | '/confidentialite'
    | '/contact'
    | '/desinscription'
    | '/legal'
    | '/mentions-legales'
    | '/method'
    | '/methode'
    | '/privacy'
    | '/unsubscribe'
    | '/books/$slug'
    | '/collections/$slug'
    | '/compagnon/$slug'
    | '/companion/$slug'
    | '/livres/$slug'
    | '/collections/'
    | '/compagnon/'
    | '/companion/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  ActivationRoute: typeof ActivationRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DesinscriptionRoute: typeof DesinscriptionRoute
  LegalRoute: typeof LegalRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodRoute: typeof MethodRoute
  MethodeRoute: typeof MethodeRoute
  PrivacyRoute: typeof PrivacyRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BooksSlugRoute: typeof BooksSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CompagnonSlugRoute: typeof CompagnonSlugRoute
  CompanionSlugRoute: typeof CompanionSlugRoute
  LivresSlugRoute: typeof LivresSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CompagnonIndexRoute: typeof CompagnonIndexRoute
  CompanionIndexRoute: typeof CompanionIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desinscription': {
      id: '/desinscription'
      path: '/desinscription'
      fullPath: '/desinscription'
      preLoaderRoute: typeof DesinscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnon/': {
      id: '/compagnon/'
      path: '/compagnon'
      fullPath: '/compagnon/'
      preLoaderRoute: typeof CompagnonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnon/$slug': {
      id: '/compagnon/$slug'
      path: '/compagnon/$slug'
      fullPath: '/compagnon/$slug'
      preLoaderRoute: typeof CompagnonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion/': {
      id: '/companion/'
      path: '/companion'
      fullPath: '/companion/'
      preLoaderRoute: typeof CompanionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion/$slug': {
      id: '/companion/$slug'
      path: '/companion/$slug'
      fullPath: '/companion/$slug'
      preLoaderRoute: typeof CompanionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livres/$slug': {
      id: '/livres/$slug'
      path: '/livres/$slug'
      fullPath: '/livres/$slug'
      preLoaderRoute: typeof LivresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  ActivationRoute: ActivationRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DesinscriptionRoute: DesinscriptionRoute,
  LegalRoute: LegalRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodRoute: MethodRoute,
  MethodeRoute: MethodeRoute,
  PrivacyRoute: PrivacyRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BooksSlugRoute: BooksSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CompagnonSlugRoute: CompagnonSlugRoute,
  CompanionSlugRoute: CompanionSlugRoute,
  LivresSlugRoute: LivresSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CompagnonIndexRoute: CompagnonIndexRoute,
  CompanionIndexRoute: CompanionIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
