/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminChiffresRouteImport } from './routes/admin.chiffres'
import { Route as AdminCompteRouteImport } from './routes/admin.compte'
import { Route as AdminExtraitsRouteImport } from './routes/admin.extraits'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AtelierIndexRouteImport } from './routes/atelier.index'
import { Route as AtelierCollectionsRouteImport } from './routes/atelier.collections'
import { Route as AtelierJournalRouteImport } from './routes/atelier.journal'
import { Route as AtelierLecteursRouteImport } from './routes/atelier.lecteurs'
import { Route as AtelierLivresRouteImport } from './routes/atelier.livres'
import { Route as AtelierMesureRouteImport } from './routes/atelier.mesure'
import { Route as AtelierPromptsRouteImport } from './routes/atelier.prompts'
import { Route as AtelierReglagesRouteImport } from './routes/atelier.reglages'
import { Route as AtelierRobotsRouteImport } from './routes/atelier.robots'
import { Route as AtelierSiteRouteImport } from './routes/atelier.site'
import { Route as AtelierConnexionRouteImport } from './routes/atelier_.connexion'
import { Route as BQr_codeRouteImport } from './routes/b.$qr_code'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CompagnonIndexRouteImport } from './routes/compagnon.index'
import { Route as CompagnonBook_slugRouteImport } from './routes/compagnon.$book_slug'
import { Route as LivresSlugRouteImport } from './routes/livres.$slug'
import { Route as ApiPublicDiagRobotRouteImport } from './routes/api/public/diag-robot'
import { Route as AtelierEtapeIdRouteImport } from './routes/atelier.etape.$id'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChiffresRoute = AdminChiffresRouteImport.update({
  id: '/chiffres',
  path: '/chiffres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompteRoute = AdminCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExtraitsRoute = AdminExtraitsRouteImport.update({
  id: '/extraits',
  path: '/extraits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AtelierIndexRoute = AtelierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierCollectionsRoute = AtelierCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierJournalRoute = AtelierJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierLecteursRoute = AtelierLecteursRouteImport.update({
  id: '/lecteurs',
  path: '/lecteurs',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierLivresRoute = AtelierLivresRouteImport.update({
  id: '/livres',
  path: '/livres',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierMesureRoute = AtelierMesureRouteImport.update({
  id: '/mesure',
  path: '/mesure',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierPromptsRoute = AtelierPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierReglagesRoute = AtelierReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierRobotsRoute = AtelierRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierSiteRoute = AtelierSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AtelierRoute,
} as any)
const AtelierConnexionRoute = AtelierConnexionRouteImport.update({
  id: '/atelier_/connexion',
  path: '/atelier/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const BQr_codeRoute = BQr_codeRouteImport.update({
  id: '/b/$qr_code',
  path: '/b/$qr_code',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagnonIndexRoute = CompagnonIndexRouteImport.update({
  id: '/compagnon/',
  path: '/compagnon/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagnonBook_slugRoute = CompagnonBook_slugRouteImport.update({
  id: '/compagnon/$book_slug',
  path: '/compagnon/$book_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LivresSlugRoute = LivresSlugRouteImport.update({
  id: '/livres/$slug',
  path: '/livres/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRobotRoute = ApiPublicDiagRobotRouteImport.update({
  id: '/api/public/diag-robot',
  path: '/api/public/diag-robot',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierEtapeIdRoute = AtelierEtapeIdRouteImport.update({
  id: '/etape/$id',
  path: '/etape/$id',
  getParentRoute: () => AtelierRoute,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/admin': typeof AdminRouteWithChildren
  '/atelier': typeof AtelierRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/admin/chiffres': typeof AdminChiffresRoute
  '/admin/compte': typeof AdminCompteRoute
  '/admin/extraits': typeof AdminExtraitsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/atelier/collections': typeof AtelierCollectionsRoute
  '/atelier/journal': typeof AtelierJournalRoute
  '/atelier/lecteurs': typeof AtelierLecteursRoute
  '/atelier/livres': typeof AtelierLivresRoute
  '/atelier/mesure': typeof AtelierMesureRoute
  '/atelier/prompts': typeof AtelierPromptsRoute
  '/atelier/reglages': typeof AtelierReglagesRoute
  '/atelier/robots': typeof AtelierRobotsRoute
  '/atelier/site': typeof AtelierSiteRoute
  '/atelier/connexion': typeof AtelierConnexionRoute
  '/b/$qr_code': typeof BQr_codeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compagnon/$book_slug': typeof CompagnonBook_slugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/atelier/': typeof AtelierIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compagnon/': typeof CompagnonIndexRoute
  '/api/public/diag-robot': typeof ApiPublicDiagRobotRoute
  '/atelier/etape/$id': typeof AtelierEtapeIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/admin/chiffres': typeof AdminChiffresRoute
  '/admin/compte': typeof AdminCompteRoute
  '/admin/extraits': typeof AdminExtraitsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/atelier/collections': typeof AtelierCollectionsRoute
  '/atelier/journal': typeof AtelierJournalRoute
  '/atelier/lecteurs': typeof AtelierLecteursRoute
  '/atelier/livres': typeof AtelierLivresRoute
  '/atelier/mesure': typeof AtelierMesureRoute
  '/atelier/prompts': typeof AtelierPromptsRoute
  '/atelier/reglages': typeof AtelierReglagesRoute
  '/atelier/robots': typeof AtelierRobotsRoute
  '/atelier/site': typeof AtelierSiteRoute
  '/atelier/connexion': typeof AtelierConnexionRoute
  '/b/$qr_code': typeof BQr_codeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compagnon/$book_slug': typeof CompagnonBook_slugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/admin': typeof AdminIndexRoute
  '/atelier': typeof AtelierIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/compagnon': typeof CompagnonIndexRoute
  '/api/public/diag-robot': typeof ApiPublicDiagRobotRoute
  '/atelier/etape/$id': typeof AtelierEtapeIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/admin': typeof AdminRouteWithChildren
  '/atelier': typeof AtelierRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methode': typeof MethodeRoute
  '/admin/chiffres': typeof AdminChiffresRoute
  '/admin/compte': typeof AdminCompteRoute
  '/admin/extraits': typeof AdminExtraitsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/atelier/collections': typeof AtelierCollectionsRoute
  '/atelier/journal': typeof AtelierJournalRoute
  '/atelier/lecteurs': typeof AtelierLecteursRoute
  '/atelier/livres': typeof AtelierLivresRoute
  '/atelier/mesure': typeof AtelierMesureRoute
  '/atelier/prompts': typeof AtelierPromptsRoute
  '/atelier/reglages': typeof AtelierReglagesRoute
  '/atelier/robots': typeof AtelierRobotsRoute
  '/atelier/site': typeof AtelierSiteRoute
  '/atelier_/connexion': typeof AtelierConnexionRoute
  '/b/$qr_code': typeof BQr_codeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/compagnon/$book_slug': typeof CompagnonBook_slugRoute
  '/livres/$slug': typeof LivresSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/atelier/': typeof AtelierIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/compagnon/': typeof CompagnonIndexRoute
  '/api/public/diag-robot': typeof ApiPublicDiagRobotRoute
  '/atelier/etape/$id': typeof AtelierEtapeIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/admin'
    | '/atelier'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/mentions-legales'
    | '/methode'
    | '/admin/chiffres'
    | '/admin/compte'
    | '/admin/extraits'
    | '/admin/pages'
    | '/atelier/collections'
    | '/atelier/journal'
    | '/atelier/lecteurs'
    | '/atelier/livres'
    | '/atelier/mesure'
    | '/atelier/prompts'
    | '/atelier/reglages'
    | '/atelier/robots'
    | '/atelier/site'
    | '/atelier/connexion'
    | '/b/$qr_code'
    | '/collections/$slug'
    | '/compagnon/$book_slug'
    | '/livres/$slug'
    | '/admin/'
    | '/atelier/'
    | '/collections/'
    | '/compagnon/'
    | '/api/public/diag-robot'
    | '/atelier/etape/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/mentions-legales'
    | '/methode'
    | '/admin/chiffres'
    | '/admin/compte'
    | '/admin/extraits'
    | '/admin/pages'
    | '/atelier/collections'
    | '/atelier/journal'
    | '/atelier/lecteurs'
    | '/atelier/livres'
    | '/atelier/mesure'
    | '/atelier/prompts'
    | '/atelier/reglages'
    | '/atelier/robots'
    | '/atelier/site'
    | '/atelier/connexion'
    | '/b/$qr_code'
    | '/collections/$slug'
    | '/compagnon/$book_slug'
    | '/livres/$slug'
    | '/admin'
    | '/atelier'
    | '/collections'
    | '/compagnon'
    | '/api/public/diag-robot'
    | '/atelier/etape/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/activation'
    | '/admin'
    | '/atelier'
    | '/confidentialite'
    | '/connexion'
    | '/contact'
    | '/mentions-legales'
    | '/methode'
    | '/admin/chiffres'
    | '/admin/compte'
    | '/admin/extraits'
    | '/admin/pages'
    | '/atelier/collections'
    | '/atelier/journal'
    | '/atelier/lecteurs'
    | '/atelier/livres'
    | '/atelier/mesure'
    | '/atelier/prompts'
    | '/atelier/reglages'
    | '/atelier/robots'
    | '/atelier/site'
    | '/atelier_/connexion'
    | '/b/$qr_code'
    | '/collections/$slug'
    | '/compagnon/$book_slug'
    | '/livres/$slug'
    | '/admin/'
    | '/atelier/'
    | '/collections/'
    | '/compagnon/'
    | '/api/public/diag-robot'
    | '/atelier/etape/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtelierRoute: typeof AtelierRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodeRoute: typeof MethodeRoute
  AtelierConnexionRoute: typeof AtelierConnexionRoute
  BQr_codeRoute: typeof BQr_codeRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CompagnonBook_slugRoute: typeof CompagnonBook_slugRoute
  LivresSlugRoute: typeof LivresSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CompagnonIndexRoute: typeof CompagnonIndexRoute
  ApiPublicDiagRobotRoute: typeof ApiPublicDiagRobotRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chiffres': {
      id: '/admin/chiffres'
      path: '/chiffres'
      fullPath: '/admin/chiffres'
      preLoaderRoute: typeof AdminChiffresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compte': {
      id: '/admin/compte'
      path: '/compte'
      fullPath: '/admin/compte'
      preLoaderRoute: typeof AdminCompteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/extraits': {
      id: '/admin/extraits'
      path: '/extraits'
      fullPath: '/admin/extraits'
      preLoaderRoute: typeof AdminExtraitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/atelier/': {
      id: '/atelier/'
      path: '/'
      fullPath: '/atelier/'
      preLoaderRoute: typeof AtelierIndexRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/collections': {
      id: '/atelier/collections'
      path: '/collections'
      fullPath: '/atelier/collections'
      preLoaderRoute: typeof AtelierCollectionsRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/journal': {
      id: '/atelier/journal'
      path: '/journal'
      fullPath: '/atelier/journal'
      preLoaderRoute: typeof AtelierJournalRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/lecteurs': {
      id: '/atelier/lecteurs'
      path: '/lecteurs'
      fullPath: '/atelier/lecteurs'
      preLoaderRoute: typeof AtelierLecteursRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/livres': {
      id: '/atelier/livres'
      path: '/livres'
      fullPath: '/atelier/livres'
      preLoaderRoute: typeof AtelierLivresRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/mesure': {
      id: '/atelier/mesure'
      path: '/mesure'
      fullPath: '/atelier/mesure'
      preLoaderRoute: typeof AtelierMesureRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/prompts': {
      id: '/atelier/prompts'
      path: '/prompts'
      fullPath: '/atelier/prompts'
      preLoaderRoute: typeof AtelierPromptsRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/reglages': {
      id: '/atelier/reglages'
      path: '/reglages'
      fullPath: '/atelier/reglages'
      preLoaderRoute: typeof AtelierReglagesRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/robots': {
      id: '/atelier/robots'
      path: '/robots'
      fullPath: '/atelier/robots'
      preLoaderRoute: typeof AtelierRobotsRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier/site': {
      id: '/atelier/site'
      path: '/site'
      fullPath: '/atelier/site'
      preLoaderRoute: typeof AtelierSiteRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/atelier_/connexion': {
      id: '/atelier_/connexion'
      path: '/atelier/connexion'
      fullPath: '/atelier/connexion'
      preLoaderRoute: typeof AtelierConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$qr_code': {
      id: '/b/$qr_code'
      path: '/b/$qr_code'
      fullPath: '/b/$qr_code'
      preLoaderRoute: typeof BQr_codeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnon/': {
      id: '/compagnon/'
      path: '/compagnon'
      fullPath: '/compagnon/'
      preLoaderRoute: typeof CompagnonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnon/$book_slug': {
      id: '/compagnon/$book_slug'
      path: '/compagnon/$book_slug'
      fullPath: '/compagnon/$book_slug'
      preLoaderRoute: typeof CompagnonBook_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livres/$slug': {
      id: '/livres/$slug'
      path: '/livres/$slug'
      fullPath: '/livres/$slug'
      preLoaderRoute: typeof LivresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag-robot': {
      id: '/api/public/diag-robot'
      path: '/api/public/diag-robot'
      fullPath: '/api/public/diag-robot'
      preLoaderRoute: typeof ApiPublicDiagRobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier/etape/$id': {
      id: '/atelier/etape/$id'
      path: '/etape/$id'
      fullPath: '/atelier/etape/$id'
      preLoaderRoute: typeof AtelierEtapeIdRouteImport
      parentRoute: typeof AtelierRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminChiffresRoute: typeof AdminChiffresRoute
  AdminCompteRoute: typeof AdminCompteRoute
  AdminExtraitsRoute: typeof AdminExtraitsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChiffresRoute: AdminChiffresRoute,
  AdminCompteRoute: AdminCompteRoute,
  AdminExtraitsRoute: AdminExtraitsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AtelierRouteChildren {
  AtelierCollectionsRoute: typeof AtelierCollectionsRoute
  AtelierJournalRoute: typeof AtelierJournalRoute
  AtelierLecteursRoute: typeof AtelierLecteursRoute
  AtelierLivresRoute: typeof AtelierLivresRoute
  AtelierMesureRoute: typeof AtelierMesureRoute
  AtelierPromptsRoute: typeof AtelierPromptsRoute
  AtelierReglagesRoute: typeof AtelierReglagesRoute
  AtelierRobotsRoute: typeof AtelierRobotsRoute
  AtelierSiteRoute: typeof AtelierSiteRoute
  AtelierIndexRoute: typeof AtelierIndexRoute
  AtelierEtapeIdRoute: typeof AtelierEtapeIdRoute
}

const AtelierRouteChildren: AtelierRouteChildren = {
  AtelierCollectionsRoute: AtelierCollectionsRoute,
  AtelierJournalRoute: AtelierJournalRoute,
  AtelierLecteursRoute: AtelierLecteursRoute,
  AtelierLivresRoute: AtelierLivresRoute,
  AtelierMesureRoute: AtelierMesureRoute,
  AtelierPromptsRoute: AtelierPromptsRoute,
  AtelierReglagesRoute: AtelierReglagesRoute,
  AtelierRobotsRoute: AtelierRobotsRoute,
  AtelierSiteRoute: AtelierSiteRoute,
  AtelierIndexRoute: AtelierIndexRoute,
  AtelierEtapeIdRoute: AtelierEtapeIdRoute,
}

const AtelierRouteWithChildren =
  AtelierRoute._addFileChildren(AtelierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRoute,
  AdminRoute: AdminRouteWithChildren,
  AtelierRoute: AtelierRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodeRoute: MethodeRoute,
  AtelierConnexionRoute: AtelierConnexionRoute,
  BQr_codeRoute: BQr_codeRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CompagnonBook_slugRoute: CompagnonBook_slugRoute,
  LivresSlugRoute: LivresSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CompagnonIndexRoute: CompagnonIndexRoute,
  ApiPublicDiagRobotRoute: ApiPublicDiagRobotRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
